
import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export const maxDuration = 60;
export const dynamic = 'force-dynamic';

const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// MOBILE-FRIENDLY SKETCH STYLE (Sync with digest/route.ts)
const EMAIL_STYLES = {
  container: "font-family: 'Verdana', 'Microsoft YaHei', sans-serif; width: 100%; max-width: 600px; margin: 0 auto; background-color: #fdfbf7; color: #333333; padding: 15px; border: 1px solid #e0e0e0; box-sizing: border-box;",
  header: "text-align: center; margin-bottom: 30px; border-bottom: 2px dashed #999; padding-bottom: 20px;",
  headerTitle: "font-size: 26px; font-weight: bold; margin: 0; color: #333; text-transform: uppercase; letter-spacing: 1px;",
  headerMeta: "font-family: monospace; color: #666; font-size: 13px; margin-top: 5px;",
  sectionContainer: "margin-bottom: 40px;",
  sectionTitle: "background-color: #333; color: #fff; padding: 6px 12px; font-size: 16px; font-weight: bold; display: inline-block; margin-bottom: 15px; border-radius: 4px; letter-spacing: 1px; max-width: 90%;",
  card: "background-color: #ffffff; border: 2px solid #444; border-radius: 8px; padding: 15px; margin-bottom: 20px; box-shadow: 4px 4px 0px #ddd;",
  cardHeader: "margin-bottom: 10px; overflow: hidden;",
  cardTitle: "font-size: 18px; font-weight: bold; line-height: 1.3; color: #000; margin: 0; margin-bottom: 8px;",
  scoreBox: "display: inline-block; background-color: #ffeb3b; border: 1px solid #333; padding: 2px 6px; border-radius: 4px; font-size: 12px; font-family: monospace; margin-bottom: 8px;",
  tags: "margin-bottom: 10px; font-size: 12px; font-family: monospace;",
  tag: "display: inline-block; background-color: #eee; padding: 2px 6px; border-radius: 4px; margin-right: 4px; margin-bottom: 4px; border: 1px solid #ccc; color: #555;",
  summaryCn: "font-size: 15px; line-height: 1.6; color: #222; margin-bottom: 6px; font-weight: 500;",
  summaryEn: "color: #777; font-size: 13px; font-style: italic; margin-bottom: 12px;",
  linkBtn: "display: inline-block; background-color: #333; color: #ffffff !important; text-decoration: none; padding: 10px 14px; font-size: 12px; font-weight: bold; border-radius: 4px; margin-top: 5px;",
  footer: "text-align: center; font-size: 12px; color: #aaa; margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; font-family: monospace;"
};

const generateEmailHtml = (data: any) => {
  const renderItems = (items: any[]) => items.map(item => `
    <div style="${EMAIL_STYLES.card}">
      <div style="${EMAIL_STYLES.cardHeader}">
         <div style="${EMAIL_STYLES.cardTitle}">${item.title}</div>
         <div style="${EMAIL_STYLES.scoreBox}">
            <b>${item.ai_score}</b> <span style="border-left:1px solid #000; margin-left:4px; padding-left:4px;">${item.ai_score_reason || 'Score'}</span>
         </div>
      </div>
      <div style="${EMAIL_STYLES.tags}">
        ${(item.tags || []).map((tag: string) => `<span style="${EMAIL_STYLES.tag}">${tag}</span>`).join('')}
      </div>
      <div style="${EMAIL_STYLES.summaryCn}">💡 ${item.summary_cn}</div>
      <div style="${EMAIL_STYLES.summaryEn}">${item.summary_en}</div>
      <div>
        <a href="${item.source_url}" target="_blank" style="${EMAIL_STYLES.linkBtn}">🔗 READ SOURCE</a>
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head><meta charset="utf-8"><title>Hajimi Morning Report</title></head>
    <body style="margin: 0; padding: 0; background-color: #f0f0f0;">
      <center>
      <!--[if mso]>
      <table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" align="center"><tr><td>
      <![endif]-->
      <div style="${EMAIL_STYLES.container}">
        <div style="${EMAIL_STYLES.header}">
          <h1 style="${EMAIL_STYLES.headerTitle}">📝 HAJIMI REPORT</h1>
          <div style="${EMAIL_STYLES.headerMeta}">
             📅 ${new Date().toLocaleDateString('zh-CN')} | DIGITAL EDITION
          </div>
        </div>
        <div style="${EMAIL_STYLES.sectionContainer}">
             <div style="${EMAIL_STYLES.sectionTitle}">🔥 TRENDS & CULTURE</div>
             ${data.social && data.social.length > 0 ? renderItems(data.social) : '<p>暂无内容</p>'}
        </div>
        <div style="${EMAIL_STYLES.sectionContainer}">
             <div style="${EMAIL_STYLES.sectionTitle}">🧬 HEALTH & SCIENCE</div>
             ${data.health && data.health.length > 0 ? renderItems(data.health) : '<p>暂无内容</p>'}
        </div>
        <div style="${EMAIL_STYLES.footer}">GENERATED BY 哈基米 AUTOMATION</div>
      </div>
      <!--[if mso]>
      </td></tr></table>
      <![endif]-->
      </center>
    </body></html>
  `;
};

const generateEmailText = (data: any) => {
  let text = `HAJIMI MORNING REPORT\nDATE: ${new Date().toLocaleDateString('zh-CN')}\n\n`;
  const processSection = (title: string, items: any[]) => {
    text += `=== ${title} ===\n\n`;
    items.forEach((item, index) => {
      text += `${index + 1}. ${item.title} [${item.ai_score}: ${item.ai_score_reason || 'N/A'}]\n摘要(CN): ${item.summary_cn}\nSummary(EN): ${item.summary_en}\nLINK: ${item.source_url}\n\n`;
    });
  };
  processSection("TRENDS", data.social || []);
  processSection("HEALTH", data.health || []);
  text += "\n----------------\nGENERATED BY 哈基米 AUTOMATION\n";
  return text;
};

export async function GET(request: Request) {
  const startTime = new Date();
  console.log(`>>> [Cron] Triggered. Time: ${startTime.toISOString()}`);

  const authHeader = request.headers.get('authorization');
  if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return new NextResponse('Unauthorized', { status: 401 });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;
    const baseUrl = process.env.GEMINI_BASE_URL || 'https://api.openai-proxy.com/v1'; 
    const model = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
    const recipientsStr = process.env.RECIPIENTS;
    const resendApiKey = process.env.RESEND_API_KEY;

    if (!apiKey || !recipientsStr || !resendApiKey) throw new Error("Missing Env Vars");

    const recipients = recipientsStr.split(',').map(r => r.trim()).filter(Boolean);

    // Prompt (Condensed)
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(today.getDate() - 1);
    const targetDateStr = yesterday.toLocaleDateString('en-US');

    const prompt = `
      You are the Hajimi Daily Editor. Today is ${today.toISOString().split('T')[0]}.
      Find 20 items from ${targetDateStr}. 10 Social/Trends, 10 Health.
      CRITICAL: LINKS MUST BE VALID. BILINGUAL SUMMARIES.
      SCORING REASON: Brief 4-word reason for score.
      Output JSON: { "social": [{"title":..., "ai_score":..., "ai_score_reason":"...", ...}], "health": [...] }
    `;

    // AI Call
    const cleanBaseUrl = baseUrl.replace(/\/+$/, '').endsWith('/v1') ? baseUrl : `${baseUrl}/v1`;
    const targetUrl = `${cleanBaseUrl}/chat/completions`;
    const payload: any = {
        model: model,
        messages: [{ role: "user", content: prompt }],
        response_format: { type: "json_object" }
    };
    if (!model.toLowerCase().includes('deepseek')) payload.tools = [{ googleSearch: {} }];

    let aiJson;
    try {
        const res = await fetch(targetUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
            body: JSON.stringify(payload)
        });
        if (!res.ok) {
             const txt = await res.text();
             console.error("Cron AI Error:", txt);
             throw new Error(txt);
        }
        aiJson = await res.json();
    } catch (e: any) {
        throw new Error(`AI Fetch Failed: ${e.message}`);
    }

    let digestData;
    const content = aiJson.choices?.[0]?.message?.content || "{}";
    try { digestData = JSON.parse(content); } 
    catch { 
         const match = content.match(/\{[\s\S]*\}/);
         digestData = match ? JSON.parse(match[0]) : { social: [], health: [] };
    }
    
    if (!digestData.social) digestData.social = [];
    if (!digestData.health) digestData.health = [];

    // Send Email
    const resend = new Resend(resendApiKey);
    const htmlContent = generateEmailHtml(digestData);
    const textContent = generateEmailText(digestData);
    const subjectLine = `Hajimi Report #${today.toISOString().split('T')[0]}`;

    const results = [];
    for (const email of recipients) {
        try {
            const { data, error } = await resend.emails.send({
                from: 'Hajimi <digest@misaki1.de5.net>',
                to: [email],
                subject: subjectLine,
                html: htmlContent,
                text: textContent,
                headers: { 'X-Entity-Ref-ID': generateId() }
            });
            results.push({ email, status: error ? 'fail' : 'success', id: data?.id });
        } catch (e: any) {
            results.push({ email, status: 'error', msg: e.message });
        }
        await new Promise(r => setTimeout(r, 1000));
    }

    return NextResponse.json({ success: true, count: digestData.social.length + digestData.health.length, results });

  } catch (error: any) {
    console.error("[Cron] Failed:", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
