
import React, { useState, useEffect, useRef } from 'react';
import { DigestData, DigestItem, LogEntry, AppStatus } from '../types';

interface PipelineViewProps {
  status: AppStatus;
  logs: LogEntry[];
  data: DigestData | null;
  onTrigger: (emails: string[]) => void;
  onReset: () => void;
}

const PREVIEW_STYLES = {
  container: "width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; color: #333; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; border: 1px solid #e5e7eb; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);",
  header: "background-color: #111827; color: #ffffff; padding: 30px 20px; text-align: center;",
  headerTitle: "font-size: 24px; font-weight: 800; margin: 0; letter-spacing: -0.5px;",
  headerMeta: "font-family: monospace; color: #9ca3af; font-size: 12px; margin-top: 8px; text-transform: uppercase;",
  sectionTitle: "background-color: #f9fafb; color: #111827; padding: 12px 20px; font-size: 14px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e5e7eb; border-top: 1px solid #e5e7eb;",
  card: "padding: 20px; border-bottom: 1px solid #f3f4f6;",
  cardHeader: "margin-bottom: 12px;",
  badge: "display: inline-block; background-color: #eff6ff; border: 1px solid #dbeafe; border-radius: 999px; padding: 2px 8px; font-size: 11px; color: #1e40af; font-weight: 600; margin-bottom: 8px;",
  title: "font-size: 18px; font-weight: 700; line-height: 1.4; color: #111827; margin: 0 0 4px 0;",
  summaryCn: "font-size: 15px; line-height: 1.6; color: #374151; margin-bottom: 6px;",
  summaryEn: "font-size: 13px; line-height: 1.5; color: #6b7280; font-style: italic; margin-bottom: 12px;",
  xhsBox: "background-color: #fff1f2; border-left: 3px solid #f43f5e; padding: 8px 12px; font-size: 12px; color: #881337; margin-bottom: 12px; border-radius: 0 4px 4px 0;",
  linkBtn: "display: inline-block; background-color: #111827; color: #fff; text-decoration: none; padding: 8px 16px; font-size: 12px; font-weight: 600; border-radius: 6px; transition: opacity 0.2s;",
  footer: "background-color: #f9fafb; padding: 30px 20px; text-align: center; font-size: 12px; color: #9ca3af;"
};

const PipelineView: React.FC<PipelineViewProps> = ({ status, logs, data, onTrigger, onReset }) => {
  const [activeTab, setActiveTab] = useState<'preview' | 'html'>('preview');
  const [emailInput, setEmailInput] = useState('');
  const [showInfo, setShowInfo] = useState(false);

  const logsEndRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    logsEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [logs]);

  const generateHtml = (data: DigestData) => {
    const renderItems = (items: DigestItem[]) => items.map(item => `
      <div style="${PREVIEW_STYLES.card}">
        <div style="${PREVIEW_STYLES.cardHeader}">
           <div style="${PREVIEW_STYLES.badge}">Score: ${item.ai_score} • ${item.ai_score_reason}</div>
           <div style="${PREVIEW_STYLES.title}">${item.title}</div>
        </div>
        
        <div style="${PREVIEW_STYLES.summaryCn}">${item.summary_cn}</div>
        
        ${item.xiaohongshu_advice ? `
          <div style="${PREVIEW_STYLES.xhsBox}">
            <strong>📕 小红书灵感:</strong> ${item.xiaohongshu_advice}
          </div>
        ` : ''}

        <div style="${PREVIEW_STYLES.summaryEn}">${item.summary_en}</div>
        
        <div>
          <a href="${item.source_url}" target="_blank" style="${PREVIEW_STYLES.linkBtn}">Read Source &rarr;</a>
        </div>
      </div>
    `).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hajimi Daily</title>
      </head>
      <body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: sans-serif;">
        <div style="width: 100%; display: flex; justify-content: center; padding: 20px 0;">
            <div style="${PREVIEW_STYLES.container}">
            <div style="${PREVIEW_STYLES.header}">
                <h1 style="${PREVIEW_STYLES.headerTitle}">HAJIMI DAILY</h1>
                <div style="${PREVIEW_STYLES.headerMeta}">
                ${new Date().toLocaleDateString()} | INTELLIGENT DIGEST
                </div>
            </div>
            
            <div style="${PREVIEW_STYLES.sectionTitle}">🌍 Global Trends</div>
            ${renderItems(data.social)}
            
            <div style="${PREVIEW_STYLES.sectionTitle}">🧬 Health & Science (Creator Mode)</div>
            ${renderItems(data.health)}
            
            <div style="${PREVIEW_STYLES.footer}">
                Generated by Hajimi Automation
            </div>
            </div>
        </div>
      </body>
      </html>
    `;
  };

  const handleDownloadLogs = () => {
    if (logs.length === 0) return;
    const content = logs.map(l => `[${l.timestamp}] [${l.type.toUpperCase()}] ${l.message}`).join('\n');
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hajimi-logs-${new Date().toISOString().slice(0,10)}.log`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const isProcessing = status === AppStatus.PROCESSING;
  const isComplete = status === AppStatus.COMPLETE && data;

  const handleRun = () => {
    if (!emailInput) { alert("请输入接收邮箱"); return; }
    const recipients = emailInput.split(/[,;\s\n]+/).map(e => e.trim()).filter(e => e.length > 0);
    if (recipients.length === 0) { alert("请输入有效的邮箱地址"); return; }
    onTrigger(recipients);
  };

  return (
    <div className="flex flex-col h-full gap-6 relative">
      <div className="flex items-center justify-between bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex-wrap gap-4 z-10">
        <div className="flex items-center gap-4">
          <div className={`h-3 w-3 rounded-full ${isProcessing ? 'bg-yellow-400 animate-pulse' : isComplete ? 'bg-green-500' : 'bg-gray-300'}`} />
          <span className="font-medium text-gray-700">{isProcessing ? 'Processing...' : isComplete ? 'Done' : 'Ready'}</span>
        </div>
        <div className="flex gap-3 items-center ml-auto flex-wrap justify-end">
          <button onClick={() => setShowInfo(true)} className="text-gray-500 hover:text-indigo-600 transition-colors text-sm font-medium mr-2">Using Gemini 2.5</button>
          <input type="text" placeholder="Email list..." value={emailInput} onChange={(e) => setEmailInput(e.target.value)} className="px-3 py-2 border border-gray-300 rounded-lg text-sm w-64 focus:outline-none focus:border-indigo-500" disabled={isProcessing} />
          <button onClick={onReset} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg text-sm">Config</button>
          <button onClick={handleRun} disabled={isProcessing || !emailInput} className={`px-6 py-2 rounded-lg text-white font-semibold shadow-md ${isProcessing || !emailInput ? 'bg-gray-400' : 'bg-indigo-600 hover:bg-indigo-700'}`}>
             {isProcessing ? 'Running...' : isComplete ? 'Resend' : 'Start'}
          </button>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0">
        <div className="lg:w-1/3 bg-gray-900 rounded-xl overflow-hidden flex flex-col shadow-lg border border-gray-800">
          <div className="bg-gray-800 px-4 py-2 flex justify-between"><span className="text-gray-400 text-xs">TERMINAL</span><button onClick={handleDownloadLogs} className="text-gray-400 hover:text-white">⬇</button></div>
          <div className="flex-1 p-4 font-mono text-xs overflow-y-auto space-y-2 text-gray-300">
            {logs.map((log, idx) => <div key={idx} className={log.type === 'error' ? 'text-red-400' : log.type === 'success' ? 'text-green-400' : 'text-blue-300'}>[{log.timestamp}] {log.message}</div>)}
            <div ref={logsEndRef} />
          </div>
        </div>

        <div className="lg:w-2/3 bg-white rounded-xl shadow-lg border border-gray-100 flex flex-col overflow-hidden">
          {data ? (
            <>
              <div className="border-b border-gray-200 flex">
                <button onClick={() => setActiveTab('preview')} className={`px-6 py-3 text-sm font-medium ${activeTab === 'preview' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-gray-500'}`}>Visual Preview</button>
                <button onClick={() => setActiveTab('html')} className={`px-6 py-3 text-sm font-medium ${activeTab === 'html' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-gray-500'}`}>Source Code</button>
              </div>
              <div className="flex-1 overflow-y-auto bg-[#eef2f5] p-4">
                {activeTab === 'preview' ? (
                  <div className="max-w-full mx-auto bg-white shadow-xl min-h-[600px] flex justify-center">
                    <iframe title="Preview" srcDoc={generateHtml(data)} className="w-full h-[800px] border-none" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts" />
                  </div>
                ) : (
                  <textarea readOnly className="w-full h-full p-4 font-mono text-xs bg-gray-50" value={generateHtml(data)} />
                )}
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-gray-400"><p>Waiting for data...</p></div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PipelineView;
