
import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export const maxDuration = 60; 
export const dynamic = 'force-dynamic';

const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// CLEAN MOBILE STYLE (Sync with Cron)
const EMAIL_STYLES = {
  container: "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; color: #333333; padding: 0; border: 1px solid #e5e7eb;",
  header: "background-color: #111827; color: #ffffff; padding: 30px 20px; text-align: center;",
  headerTitle: "font-size: 24px; font-weight: 800; margin: 0; letter-spacing: -0.5px;",
  headerMeta: "font-family: monospace; color: #9ca3af; font-size: 12px; margin-top: 8px; text-transform: uppercase;",
  sectionTitle: "background-color: #f3f4f6; color: #111827; padding: 12px 20px; font-size: 16px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e5e7eb; border-top: 1px solid #e5e7eb;",
  card: "padding: 20px; border-bottom: 1px solid #f3f4f6;",
  cardTop: "margin-bottom: 8px;",
  title: "font-size: 18px; font-weight: 700; line-height: 1.4; color: #111827; display: block; margin-bottom: 6px; text-decoration: none;",
  badgeContainer: "display: inline-block; background-color: #eff6ff; border: 1px solid #dbeafe; border-radius: 999px; padding: 2px 8px; font-size: 11px; color: #1e40af; font-weight: 600; margin-bottom: 8px;",
  summaryCn: "font-size: 15px; line-height: 1.6; color: #374151; margin-bottom: 6px; display: block;",
  summaryEn: "font-size: 13px; line-height: 1.5; color: #6b7280; font-style: italic; display: block; margin-bottom: 12px;",
  linkBtn: "display: inline-block; background-color: #111827; color: #ffffff !important; text-decoration: none; padding: 8px 16px; font-size: 12px; font-weight: 600; border-radius: 6px;",
  footer: "background-color: #f9fafb; padding: 30px 20px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb;"
};

const generateEmailHtml = (data: any) => {
  const renderItems = (items: any[]) => items.map(item => `
    <div style="${EMAIL_STYLES.card}">
      <div style="${EMAIL_STYLES.cardTop}">
         <div style="${EMAIL_STYLES.badgeContainer}">
             Score: ${item.ai_score} • ${item.ai_score_reason || 'Trending'}
         </div>
         <a href="${item.source_url}" style="${EMAIL_STYLES.title}" target="_blank">${item.title}</a>
      </div>
      
      <span style="${EMAIL_STYLES.summaryCn}">
        ${item.summary_cn}
      </span>
      <span style="${EMAIL_STYLES.summaryEn}">
        ${item.summary_en}
      </span>
      
      <div style="margin-top: 8px;">
        <a href="${item.source_url}" target="_blank" style="${EMAIL_STYLES.linkBtn}">Read Source &rarr;</a>
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hajimi Daily</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
      <center>
      <div style="${EMAIL_STYLES.container}">
        <div style="${EMAIL_STYLES.header}">
          <h1 style="${EMAIL_STYLES.headerTitle}">HAJIMI DAILY</h1>
          <div style="${EMAIL_STYLES.headerMeta}">
             ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).toUpperCase()} • INTELLIGENT DIGEST
          </div>
        </div>
        
        <div style="${EMAIL_STYLES.sectionTitle}">🌍 Global Trends</div>
        ${data.social && data.social.length > 0 ? renderItems(data.social) : '<div style="padding:20px;">No items found.</div>'}
        
        <div style="${EMAIL_STYLES.sectionTitle}">🧬 Health & Science</div>
        ${data.health && data.health.length > 0 ? renderItems(data.health) : '<div style="padding:20px;">No items found.</div>'}
        
        <div style="${EMAIL_STYLES.footer}">
          Generated by Hajimi Automation System
        </div>
      </div>
      </center>
    </body>
    </html>
  `;
};

const generateEmailText = (data: any) => {
  let text = `HAJIMI DAILY\nDATE: ${new Date().toLocaleDateString()}\n\n`;
  const processSection = (title: string, items: any[]) => {
    text += `=== ${title} ===\n\n`;
    if (!items || items.length === 0) {
      text += "暂无内容\n\n";
      return;
    }
    items.forEach((item, index) => {
      text += `${index + 1}. ${item.title} [${item.ai_score}: ${item.ai_score_reason || 'N/A'}]\n`;
      text += `摘要(CN): ${item.summary_cn}\n`;
      text += `Summary(EN): ${item.summary_en}\n`;
      text += `LINK: ${item.source_url}\n\n`;
    });
  };
  processSection("GLOBAL", data.social);
  processSection("HEALTH", data.health);
  text += "\n----------------\nGenerated by Hajimi Automation\n";
  return text;
};

export async function POST(request: Request) {
  try {
    const resendApiKey = process.env.RESEND_API_KEY;
    if (!resendApiKey) return NextResponse.json({ error: 'Missing Mailer API Key' }, { status: 500 });
    const resend = new Resend(resendApiKey);

    const body = await request.json();
    const { recipients, digestData } = body;

    if (!recipients || !digestData) return NextResponse.json({ error: 'Missing data' }, { status: 400 });

    const htmlContent = generateEmailHtml(digestData);
    const textContent = generateEmailText(digestData);
    const subjectLine = `Hajimi Daily #${new Date().toISOString().split('T')[0]}`;

    console.log(`Sending to ${recipients.length} recipients...`);

    const results = [];
    for (const recipientEmail of recipients) {
        try {
            const { data, error } = await resend.emails.send({
                from: 'Hajimi <digest@misaki1.de5.net>', 
                to: [recipientEmail], 
                subject: subjectLine,
                html: htmlContent,
                text: textContent,
                headers: { 'X-Entity-Ref-ID': generateId() }
            });
            results.push({ email: recipientEmail, status: error ? 'failed' : 'success', id: data?.id, error });
        } catch (e: any) {
            results.push({ email: recipientEmail, status: 'error', message: e.message });
        }
        await new Promise(resolve => setTimeout(resolve, 500));
    }
    return NextResponse.json({ success: true, details: results });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
