
import { NextResponse } from 'next/server';
import { Resend } from 'resend';

// Vercel Serverless Function 配置
export const maxDuration = 60; 
export const dynamic = 'force-dynamic';

// 简单的 ID 生成器
const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// DIGITAL PRINT STYLE (Inline CSS for Email Clients)
const EMAIL_STYLES = {
  container: "font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 3px solid #000000; color: #000000;",
  
  header: "background-color: #000000; color: #ffffff; padding: 24px 16px; border-bottom: 3px solid #000000;",
  headerTitle: "font-family: 'Impact', 'Arial Black', sans-serif; text-transform: uppercase; font-size: 32px; letter-spacing: -1px; line-height: 1; margin: 0;",
  headerMeta: "font-family: 'Courier New', Courier, monospace; font-size: 12px; margin-top: 8px; letter-spacing: 1px; opacity: 0.8;",
  
  sectionTitle: "background-color: #000000; color: #ffffff; font-family: 'Impact', 'Arial Black', sans-serif; font-size: 18px; text-transform: uppercase; padding: 4px 12px; display: inline-block; margin: 24px 0 0 -3px; transform: skewX(-10deg);",
  
  card: "border-bottom: 2px solid #000000; padding: 16px; display: block; background-color: #ffffff;",
  
  cardHeaderRow: "display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; margin-bottom: 8px;",
  cardTitle: "font-family: 'Helvetica Neue', Arial, sans-serif; font-weight: 900; font-size: 18px; line-height: 1.1; color: #000000; margin: 0; flex: 1;",
  scoreBadge: "background-color: #000000; color: #ffffff; font-family: 'Courier New', monospace; font-weight: bold; font-size: 14px; padding: 2px 6px; border-radius: 0; min-width: 32px; text-align: center;",
  
  tagsRow: "margin-bottom: 8px; font-size: 10px; text-transform: uppercase; font-weight: bold; font-family: monospace;",
  tag: "display: inline-block; background-color: #f0f0f0; border: 1px solid #000; padding: 1px 4px; margin-right: 4px; color: #000;",
  
  summaryCn: "font-family: Georgia, 'Times New Roman', serif; font-size: 15px; line-height: 1.4; color: #000000; margin-bottom: 6px; font-weight: 500;",
  
  footer: "border-top: 3px solid #000000; background-color: #f4f4f4; padding: 20px; text-align: center; font-family: 'Courier New', monospace; font-size: 11px; color: #000000; font-weight: bold; text-transform: uppercase;"
};

// 辅助函数：生成 HTML 字符串
const generateEmailHtml = (data: any) => {
  const renderItems = (items: any[]) => items.map(item => `
    <div style="${EMAIL_STYLES.card}">
      <div style="margin-bottom: 8px;">
         <div style="float: right; ${EMAIL_STYLES.scoreBadge}">${item.ai_score || '-'}</div>
         <div style="${EMAIL_STYLES.cardTitle}">${item.title}</div>
         <div style="clear: both;"></div>
      </div>
      
      <div style="${EMAIL_STYLES.tagsRow}">
        ${(item.tags || []).map((tag: string) => `<span style="${EMAIL_STYLES.tag}">${tag}</span>`).join('')}
        <span style="opacity:0.5; margin-left: 5px;">${item.source_name}</span>
      </div>

      <div style="${EMAIL_STYLES.summaryCn}">${item.summary_cn}</div>
      <div>
        <a href="${item.source_url}" style="color: #000; text-decoration: underline; font-size: 11px; font-family: monospace;" target="_blank">READ FULL ARTICLE &rarr;</a>
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Daily Pulse</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f4; -webkit-font-smoothing: antialiased;">
      <div style="${EMAIL_STYLES.container}">
        <div style="${EMAIL_STYLES.header}">
          <h1 style="${EMAIL_STYLES.headerTitle}">Daily Pulse</h1>
          <div style="${EMAIL_STYLES.headerMeta}">
             ISSUE: ${new Date().toLocaleDateString('en-GB').toUpperCase()} <span style="float:right">DIGITAL EDITION</span>
          </div>
        </div>
        
        <div style="padding: 0 16px;">
             <div style="${EMAIL_STYLES.sectionTitle}">PULSE // SOCIAL</div>
        </div>
        ${data.social && data.social.length > 0 ? renderItems(data.social) : '<p style="padding:16px;">暂无内容</p>'}
        
        <div style="padding: 0 16px;">
             <div style="${EMAIL_STYLES.sectionTitle}">LAB // SCIENCE</div>
        </div>
        ${data.health && data.health.length > 0 ? renderItems(data.health) : '<p style="padding:16px;">暂无内容</p>'}
        
        <div style="${EMAIL_STYLES.footer}">
          GENERATED BY GEMINI 2.5 • AI AUTOMATION<br/>
          <span style="opacity: 0.6">To unsubscribe, please reply to this email.</span>
        </div>
      </div>
    </body>
    </html>
  `;
};

// 新增辅助函数：生成纯文本字符串
const generateEmailText = (data: any) => {
  let text = `DAILY PULSE - DIGITAL EDITION\nISSUE: ${new Date().toLocaleDateString('zh-CN')}\n\n`;

  const processSection = (title: string, items: any[]) => {
    text += `=== ${title} ===\n\n`;
    if (!items || items.length === 0) {
      text += "暂无内容\n\n";
      return;
    }
    items.forEach((item, index) => {
      text += `${index + 1}. ${item.title} [AI Score: ${item.ai_score}]\n`;
      text += `TAGS: ${(item.tags || []).join(', ')}\n`;
      text += `摘要: ${item.summary_cn}\n`;
      text += `来源: ${item.source_name}\n`;
      text += `链接: ${item.source_url}\n\n`;
    });
  };

  processSection("PULSE // SOCIAL", data.social);
  processSection("LAB // SCIENCE", data.health);
  
  text += "\n----------------\nGENERATED BY GEMINI 2.5\n";
  return text;
};

export async function POST(request: Request) {
  try {
    const resendApiKey = process.env.RESEND_API_KEY;
    
    if (!resendApiKey) {
        console.error("Missing RESEND_API_KEY environment variable");
        return NextResponse.json({ error: 'Server configuration error: Missing Mailer API Key' }, { status: 500 });
    }

    const resend = new Resend(resendApiKey);

    const body = await request.json();
    const { recipients, digestData } = body;

    if (!recipients || !Array.isArray(recipients) || recipients.length === 0 || !digestData) {
      return NextResponse.json({ error: 'Missing recipients list or data' }, { status: 400 });
    }

    const htmlContent = generateEmailHtml(digestData);
    const textContent = generateEmailText(digestData);
    const subjectLine = `Daily Pulse #${new Date().toISOString().split('T')[0]}`;

    const results = [];
    
    console.log(`Starting to send emails to ${recipients.length} recipients...`);

    for (const recipientEmail of recipients) {
        try {
            const { data, error } = await resend.emails.send({
                from: 'Daily Pulse <digest@misaki1.de5.net>', 
                to: [recipientEmail], 
                subject: subjectLine,
                html: htmlContent,
                text: textContent,
                headers: {
                    'X-Entity-Ref-ID': generateId(), // 使用自定义生成器
                }
            });
            
            if (error) {
                console.error(`Failed to send to ${recipientEmail}:`, error);
                results.push({ email: recipientEmail, status: 'failed', error });
            } else {
                results.push({ email: recipientEmail, status: 'success', id: data?.id });
            }
        } catch (e: any) {
            console.error(`Exception sending to ${recipientEmail}:`, e);
            results.push({ email: recipientEmail, status: 'error', message: e.message });
        }

        await new Promise(resolve => setTimeout(resolve, 1000));
    }
    
    const successCount = results.filter(r => r.status === 'success').length;
    const failCount = results.length - successCount;

    if (successCount === 0 && failCount > 0) {
         return NextResponse.json({ error: 'All emails failed to send', details: results }, { status: 500 });
    }

    return NextResponse.json({ 
        success: true, 
        message: `Sent ${successCount} emails, ${failCount} failed.`,
        details: results 
    });

  } catch (error: any) {
    console.error('Email dispatch error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
