
import { NextResponse } from 'next/server';
import { Resend } from 'resend';

// Vercel Serverless Function 配置
export const maxDuration = 60; 
export const dynamic = 'force-dynamic';

const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// SKETCH / REPORT STYLE FOR EMAIL CLIENTS (INLINE CSS)
const EMAIL_STYLES = {
  // Global Container - Beige Paper Look
  container: "font-family: 'Verdana', 'Helvetica', sans-serif; max-width: 620px; margin: 0 auto; background-color: #fdfbf7; color: #333333; padding: 20px; border: 1px solid #e0e0e0;",
  
  // Header
  header: "text-align: center; margin-bottom: 30px; border-bottom: 2px dashed #999; padding-bottom: 20px;",
  headerTitle: "font-size: 28px; font-weight: bold; margin: 0; color: #333; text-transform: uppercase; letter-spacing: 2px;",
  headerMeta: "font-family: monospace; color: #666; font-size: 14px; margin-top: 5px;",
  
  // Section Headers - Highlight Marker Look
  sectionContainer: "margin-bottom: 40px;",
  sectionTitle: "background-color: #333; color: #fff; padding: 6px 12px; font-size: 16px; font-weight: bold; display: inline-block; margin-bottom: 15px; border-radius: 4px; letter-spacing: 1px;",
  
  // Cards - White Box on Beige
  card: "background-color: #ffffff; border: 2px solid #444; border-radius: 8px; padding: 15px; margin-bottom: 20px; box-shadow: 4px 4px 0px #ddd;",
  
  // Card Details
  cardHeader: "margin-bottom: 10px;",
  cardTitle: "font-size: 18px; font-weight: bold; line-height: 1.3; color: #000; margin: 0; margin-bottom: 4px;",
  
  tags: "margin-bottom: 10px; font-size: 12px; font-family: monospace;",
  tag: "background-color: #eee; padding: 2px 6px; border-radius: 4px; margin-right: 5px; border: 1px solid #ccc; color: #555;",
  
  summaryCn: "font-size: 15px; line-height: 1.6; color: #222; margin-bottom: 6px; font-weight: 500;",
  summaryEn: "color: #777; font-size: 13px; font-style: italic; margin-bottom: 12px;",
  
  linkBtn: "display: inline-block; background-color: #333; color: #ffffff !important; text-decoration: none; padding: 8px 12px; font-size: 12px; font-weight: bold; border-radius: 4px;",
  
  footer: "text-align: center; font-size: 12px; color: #aaa; margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; font-family: monospace;"
};

const generateEmailHtml = (data: any) => {
  const renderItems = (items: any[]) => items.map(item => `
    <div style="${EMAIL_STYLES.card}">
      <div style="${EMAIL_STYLES.cardHeader}">
         <div style="${EMAIL_STYLES.cardTitle}">${item.title}</div>
      </div>
      
      <div style="${EMAIL_STYLES.tags}">
        <span style="float:right; color:#888;">Score: ${item.ai_score}</span>
        ${(item.tags || []).map((tag: string) => `<span style="${EMAIL_STYLES.tag}">${tag}</span>`).join('')}
      </div>

      <div style="${EMAIL_STYLES.summaryCn}">💡 ${item.summary_cn}</div>
      <div style="${EMAIL_STYLES.summaryEn}">${item.summary_en}</div>
      
      <div style="margin-top: 10px;">
        <a href="${item.source_url}" target="_blank" style="${EMAIL_STYLES.linkBtn}">🔗 READ SOURCE &rarr;</a>
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hajimi Morning Report</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f0f0f0; -webkit-font-smoothing: antialiased;">
      <center>
      <div style="${EMAIL_STYLES.container}">
        <div style="${EMAIL_STYLES.header}">
          <h1 style="${EMAIL_STYLES.headerTitle}">📝 HAJIMI REPORT</h1>
          <div style="${EMAIL_STYLES.headerMeta}">
             📅 ${new Date().toLocaleDateString('zh-CN')} | DIGITAL EDITION
          </div>
        </div>
        
        <div style="${EMAIL_STYLES.sectionContainer}">
             <div style="${EMAIL_STYLES.sectionTitle}">🔥 TRENDS & CULTURE</div>
             ${data.social && data.social.length > 0 ? renderItems(data.social) : '<p>暂无内容</p>'}
        </div>
        
        <div style="${EMAIL_STYLES.sectionContainer}">
             <div style="${EMAIL_STYLES.sectionTitle}">🧬 HEALTH & SCIENCE</div>
             ${data.health && data.health.length > 0 ? renderItems(data.health) : '<p>暂无内容</p>'}
        </div>
        
        <div style="${EMAIL_STYLES.footer}">
          GENERATED BY 哈基米 AUTOMATION
        </div>
      </div>
      </center>
    </body>
    </html>
  `;
};

const generateEmailText = (data: any) => {
  let text = `HAJIMI MORNING REPORT\nDATE: ${new Date().toLocaleDateString('zh-CN')}\n\n`;

  const processSection = (title: string, items: any[]) => {
    text += `=== ${title} ===\n\n`;
    if (!items || items.length === 0) {
      text += "暂无内容\n\n";
      return;
    }
    items.forEach((item, index) => {
      text += `${index + 1}. ${item.title} [Score: ${item.ai_score}]\n`;
      text += `摘要(CN): ${item.summary_cn}\n`;
      text += `Summary(EN): ${item.summary_en}\n`;
      text += `LINK: ${item.source_url}\n\n`;
    });
  };

  processSection("TRENDS", data.social);
  processSection("HEALTH", data.health);
  
  text += "\n----------------\nGENERATED BY 哈基米 AUTOMATION\n";
  return text;
};

export async function POST(request: Request) {
  try {
    const resendApiKey = process.env.RESEND_API_KEY;
    if (!resendApiKey) return NextResponse.json({ error: 'Missing Mailer API Key' }, { status: 500 });
    const resend = new Resend(resendApiKey);

    const body = await request.json();
    const { recipients, digestData } = body;

    if (!recipients || !digestData) return NextResponse.json({ error: 'Missing data' }, { status: 400 });

    const htmlContent = generateEmailHtml(digestData);
    const textContent = generateEmailText(digestData);
    const subjectLine = `Hajimi Report #${new Date().toISOString().split('T')[0]}`;

    console.log(`Sending to ${recipients.length} recipients...`);

    const results = [];
    for (const recipientEmail of recipients) {
        try {
            const { data, error } = await resend.emails.send({
                from: 'Hajimi <digest@misaki1.de5.net>', 
                to: [recipientEmail], 
                subject: subjectLine,
                html: htmlContent,
                text: textContent,
                headers: { 'X-Entity-Ref-ID': generateId() }
            });
            results.push({ email: recipientEmail, status: error ? 'failed' : 'success', id: data?.id, error });
        } catch (e: any) {
            results.push({ email: recipientEmail, status: 'error', message: e.message });
        }
        await new Promise(resolve => setTimeout(resolve, 500));
    }
    return NextResponse.json({ success: true, details: results });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
